// ============================================================
// MADEIRA MEDICAL GROUP — EDITABLE CONTENT
// Edit this file to update any text on the site.
// ============================================================

export const SITE = {
  name: "Madeira Medical Group",
  tagline: "Puerto Vallarta",
  phone: "+52 322 293-6235",
  email: "anamaria@homia.mx",
  address: "Havre #239-101, Col. Díaz Ordaz, Puerto Vallarta, Jalisco",
  whatsapp: "523222936235",
  mapsEmbed:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3734.4!2d-105.2286648!3d20.6370772!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8421454e08759ccd%3A0x8ebaa9f70f42f09c!2sMadeira%20Medical%20Group%20-%20Consultorios%20m%C3%A9dicos!5e0!3m2!1ses!2smx!4v1714950000000!5m2!1ses!2smx",
};

export const NAV = {
  links: [
    { label: "Inicio", href: "#inicio" },
    { label: "Agendar Consulta", href: "#agenda" },
    { label: "Rentar Consultorio", href: "#renta" },
    { label: "Especialidades", href: "#especialidades" },
    { label: "Médicos", href: "#medicos" },
    { label: "Contacto", href: "#contacto" },
  ],
  ctaLabel: "Rentar Consultorio",
  ctaHref: "#renta",
};

export const HERO = {
  badge: "Último consultorio disponible",
  headline: "Madeira Medical Group",
  subheadline: "Puerto Vallarta",
  body: "Consultorios modernos en la zona con la más alta densidad médica de Puerto Vallarta. Secretaria e infraestructura incluidas desde el primer día.",
  cta1: { label: "Contáctanos", href: "#contacto" },
  cta2: { label: "Agendar Cita", href: "#agenda" },
};

export const AGENDA = {
  headline: "Agenda una consulta",
  body: "¿Eres médico y buscas un espacio profesional para atender a tus pacientes? Contáctanos y te asesoramos sin costo.",
  cta: { label: "Agendar ahora →", href: `https://wa.me/523222936235?text=Hola,%20quiero%20agendar%20una%20consulta%20para%20rentar%20consultorio.` },
};

export const LOCATION = {
  badge: "Ubicación privilegiada",
  headline: "En el corazón de Versalles, Puerto Vallarta",
  body: "Nuestros consultorios están ubicados en la zona con mayor densidad de Puerto Vallarta. Versalles es un ícono amado por turistas y residentes extranjeros, con planeación urbana organizada y acceso privilegiado para tus pacientes.",
  stats: [
    { value: "55+", label: "Familias en el complejo Punto Madeira" },
    { value: "#1", label: "Zona de turismo médico en PV" },
    { value: "100%", label: "Infraestructura incluida" },
  ],
};

export const RENTAL = {
  badge: "Renta tu consultorio hoy",
  headline: "Elige la mejor opción para tu práctica médica",
  body: "Madeira Medical Group cuenta con las mejores instalaciones para que brindes atención de calidad a tus pacientes desde el primer día. Todo incluido, sin complicaciones.",
  features: [
    {
      icon: "🏥",
      title: "Consultorios modernos",
      description: "Espacios equipados con mobiliario médico de alta calidad y acabados premium.",
    },
    {
      icon: "👩‍💼",
      title: "Secretaria incluida",
      description: "Gestión de citas y atención al paciente desde que llegas.",
    },
    {
      icon: "📅",
      title: "Gestión de consultas",
      description: "Sistema de agenda profesional y recordatorios automáticos para tus pacientes.",
    },
    {
      icon: "📶",
      title: "Internet de alta velocidad",
      description: "Conectividad empresarial incluida para expedientes digitales y telemedicina.",
    },
    {
      icon: "🅿️",
      title: "Estacionamiento",
      description: "Acceso para médicos y pacientes dentro del complejo Punto Madeira.",
    },
    {
      icon: "💰",
      title: "Retorno de inversión inmediato",
      description: "Saca el máximo provecho desde el primer mes con una ubicación de alto tráfico.",
    },
  ],
  cta1: { label: "Descargar precios", href: "#contacto" },
  cta2: { label: "Rentar ahora", href: `https://wa.me/523222936235?text=Quiero%20rentar%20un%20consultorio%20en%20Madeira%20Medical%20Group.` },
};

export const DOCTORS = {
  badge: "Médicos Especialistas",
  headline: "Nuestro equipo de especialistas",
  body: "Contamos con los mejores especialistas en diversas áreas médicas para ofrecer atención integral a todos nuestros pacientes.",
  specialties: [
    "Cirugía Oral y Maxilofacial",
    "Ortodoncia e Invisalign",
    "Ortopedia Maxilofacial",
    "Psicología Clínica",
    "Armonización Facial",
    "Rehabilitación Dental",
    "Cirugía Plástica",
    "Endocrinología",
    "Laboratorio Clínico",
    "Ginecología y Obstetricia",
    "Pediatría",
    "Medicina Regenerativa",
    "Implantología",
    "Nutrición",
    "Medicina Interna",
    "Cardiología",
    "Dermatología",
    "Urología",
    "Medicina Alternativa",
    "Alergología e Inmunología",
  ],
};

export const DOCTORS_LIST = [
  {
    slug: "dra_mar_palacios",
    name: "Dra. Mar Palacios",
    specialty: "Ortodoncia · Invisalign · Ortopedia Maxilofacial",
    phone: "322 293 6235",
    photo: "/doctors/dra_mar_palacios.jpg",
    services: [
      "Ortodoncia",
      "Invisalign",
      "Ortopedia maxilofacial",
      "Limpieza dental adultos e infantil",
      "Blanqueamiento",
      "Protocolo ICON de desmanchado dental",
      "Guarda oclusal nocturno",
      "Odontología general",
    ],
  },
  {
    slug: "dra_karla_marcela_figueroa_aguilar",
    name: "Dra. Karla Marcela Figueroa Aguilar",
    specialty: "Odontología Restauradora Avanzada e Implantes",
    phone: "322-159-0014",
    photo: "/doctors/dra_karla_marcela_figueroa_aguilar.jpg",
    services: [
      "Diseño de sonrisa",
      "Implantes dentales",
      "Limpiezas dentales y blanqueamientos",
      "Remoción segura de amalgamas",
      "Rehabilitación de bruxismo",
      "Protocolo ICON de desmanchado dental",
      "Odontología integral",
    ],
  },
  {
    slug: "dra_sarai_bethzabee_rivera_ramos",
    name: "Dra. Saraí Bethzabee Rivera Ramos",
    specialty: "Odontología Integral · Rehabilitación Oral",
    phone: "322 118 1141",
    photo: "/doctors/dra_sarai_bethzabee_rivera_ramos.jpg",
    services: [
      "Ortodoncia",
      "Endodoncia",
      "Exodoncia",
      "Odontopediatría",
      "Cirugía de terceros molares",
      "Rehabilitación oral",
      "Prostodoncia",
    ],
  },
  {
    slug: "dra_angela_goretti_robles_ibarra",
    name: "Dra. Ángela Goretti Robles Ibarra",
    specialty: "Odontología · Armonización Facial",
    phone: "322-142-6017",
    photo: "/doctors/dra_angela_goretti_robles_ibarra.jpg",
    services: [
      "Limpieza dental",
      "Blanqueamiento",
      "Diseño de sonrisa con resina",
      "Rellenos con ácido hialurónico",
      "Aplicación de bótox",
      "Bioestimulación de colágeno y elastina",
      "Bichectomía",
      "Hilos tensores en rostro",
      "Carillas dentales",
    ],
  },
  {
    slug: "dr_jose_emanuel_martinez_rojo",
    name: "Dr. José Emanuel Martínez Rojo",
    specialty: "Cirujano Maxilofacial",
    phone: "331 834 3785",
    photo: "/doctors/dr_jose_emanuel_martinez_rojo.jpg",
    services: [
      "Patología oral y maxilofacial",
      "Anomalías dentofaciales",
      "Cirugía ortognática",
      "Traumatismos faciales",
      "Articulación temporomandibular",
      "Mentoplastia ósea",
      "Reconstrucción maxilofacial",
      "Implantología avanzada",
    ],
  },
  {
    slug: "dra_daniela_anahi_ciambelli_romero",
    name: "Dra. Daniela Anahí Ciambelli Romero",
    specialty: "Cirugía Plástica, Estética y Reconstructiva",
    phone: "322-200-2022",
    photo: "/doctors/dra_daniela_anahi_ciambelli_romero.jpg",
    services: [
      "Cirugía plástica estética y reconstructiva",
      "Toxina botulínica y rellenos",
      "Otoplastía, blefaroplastia, bichectomía",
      "Liposucción de cuello",
      "Microneedle facial y corporal",
      "Cirugía facial",
    ],
  },
  {
    slug: "dr_marco_antonio_rodriguez_perez",
    name: "Dr. Marco Antonio Rodríguez Pérez",
    specialty: "Medicina Estética y Antienvejecimiento",
    phone: "322 288 7637",
    photo: "/doctors/dr_marco_antonio_rodriguez_perez.jpg",
    services: [
      "Toxina botulínica tipo A",
      "Rellenos dérmicos",
      "Peelings",
      "Microneedling",
      "Escleroterapia",
      "Bioestimuladores de colágeno",
      "Rejuvenecimiento no quirúrgico",
    ],
  },
  {
    slug: "dra_esli_perez_castro",
    name: "Dra. Esli Pérez Castro",
    specialty: "Medicina Regenerativa Bioestética",
    phone: "322 216 8611",
    photo: "/doctors/dra_esli_perez_castro.jpg",
    services: [
      "Terapia de reemplazo hormonal bioidéntica",
      "Bioestimuladores de colágeno",
      "Terapia celular",
      "Terapia de biológicos (implante placentario)",
      "Toxina botulínica tipo A",
      "Rellenos faciales",
      "Microneedling",
      "Faciales clínicos",
    ],
  },
  {
    slug: "dr_edgar_martin_hernandez_jimenez",
    name: "Dr. Edgar Martín Hernández Jiménez",
    specialty: "Medicina Estética y Regenerativa",
    phone: "322-120-0894",
    photo: "/doctors/dr_edgar_martin_hernandez_jimenez.jpg",
    services: [
      "Consulta familiar / domicilio",
      "Rutina cuidados de piel",
      "Bioestimuladores",
      "Pérdida de peso",
      "Terapia celular y exosomas",
      "Moldeamiento corporal",
      "P-Shot / disfunción sexual",
    ],
  },
  {
    slug: "dra_lidia_ivonne_moreno_rodriguez",
    name: "Dra. Lidia Ivonne Moreno Rodríguez",
    specialty: "Endocrinología Clínica Adultos",
    phone: "322-108-8804",
    photo: "/doctors/dra_lidia_ivonne_moreno_rodriguez.jpg",
    services: [
      "Tiroides",
      "Sobrepeso y obesidad",
      "Diabetes tipo 1 y 2",
      "Resistencia a la insulina",
      "Ovarios poliquísticos",
      "Infertilidad",
      "Síndrome de Cushing",
    ],
  },
  {
    slug: "dra_fernanda_sanchez",
    name: "Dra. Fernanda Sánchez",
    specialty: "Endocrinología Pediátrica",
    phone: "322 293 6235",
    photo: "/doctors/dra_fernanda_sanchez.jpg",
    services: [
      "Problemas de crecimiento",
      "Diabetes mellitus",
      "Obesidad y sobrepeso",
      "Trastornos de pubertad",
      "Tiroides",
      "Metabolismo de calcio",
      "Ovarios y testículos",
    ],
  },
  {
    slug: "dra_jessica_nitardy",
    name: "Dra. Jessica Nitardy",
    specialty: "Especialista",
    phone: "322 293 6235",
    photo: "/doctors/dra_jessica_nitardy.jpg",
    services: [],
  },
  {
    slug: "dr_mario_alejandro_rendon_acosta",
    name: "Dr. Mario Alejandro Rendón Acosta",
    specialty: "Ginecología y Obstetricia",
    phone: "322 293 6235",
    photo: "/doctors/dr_mario_alejandro_rendon_acosta.jpg",
    services: [
      "Consulta ginecológica general",
      "Control de embarazo",
      "Ultrasonido obstétrico 3D/4D",
      "Infertilidad y tratamientos",
      "Climaterio / menopausia y TRH",
      "Enfermedades de transmisión sexual",
      "Rejuvenecimiento íntimo con láser CO2",
    ],
  },
  {
    slug: "dr_rogelio_rios_esparza",
    name: "Dr. Rogelio Ríos Esparza",
    specialty: "Ginecología",
    phone: "322-378-8686",
    photo: "/doctors/dr_rogelio_rios_esparza.jpg",
    services: [
      "Control de embarazo de bajo y alto riesgo",
      "Ultrasonido 3D y 4D",
      "Control ginecológico",
      "Climaterio y menopausia",
      "Abordaje de infertilidad",
      "Manejo de endometriosis",
      "Cirugía ginecológica de mínima invasión",
    ],
  },
  {
    slug: "dra_devy_michelle_ojeda_castellon",
    name: "Dra. Devy Michelle Ojeda Castellón",
    specialty: "Ginecología",
    phone: "322-194-6628",
    photo: "/doctors/dra_devy_michelle_ojeda_castellon.jpg",
    services: [
      "Control de embarazo de bajo y alto riesgo",
      "Ultrasonido 3D y 4D",
      "Control ginecológico",
      "Climaterio y menopausia",
      "Abordaje de infertilidad",
      "Manejo de endometriosis",
      "Cirugía ginecológica de mínima invasión",
    ],
  },
  {
    slug: "dr_carlos_omar_zuniga_reyes",
    name: "Dr. Carlos Omar Zúñiga Reyes",
    specialty: "Alergia e Inmunología Clínica · Pediatría",
    phone: "322-279-5733",
    photo: "/doctors/dr_carlos_omar_zuniga_reyes.jpg",
    services: [
      "Alergia e inmunología clínica",
      "Pruebas de alergia e inmunoterapia",
      "Vacuna para alergia",
      "Pediatría (recién nacidos a 18 años)",
    ],
  },
  {
    slug: "dra_adriana_turrubiates_flores",
    name: "Dra. Adriana Turrubiates Flores",
    specialty: "Geriatría",
    phone: "322 293 6235",
    photo: "/doctors/dra_adriana_turrubiates_flores.jpg",
    services: [
      "Atención integral del adulto mayor",
      "Test de memoria y demencias",
      "Rehabilitación del adulto mayor",
      "Cuidados paliativos",
      "Manejo del dolor crónico",
      "Trastornos del sueño y alimentación",
      "Electrocardiograma",
    ],
  },
  {
    slug: "dr_diego_alejandro_arce_lopez",
    name: "Dr. Diego Alejandro Arce López",
    specialty: "Medicina Interna",
    phone: "322-293-6235",
    photo: "/doctors/dr_diego_alejandro_arce_lopez.jpg",
    services: [
      "Consulta médica de especialidad",
      "Interpretación de laboratorios",
      "Valoración preoperatoria",
      "Electrocardiograma",
      "Control metabólico completo",
    ],
  },
  {
    slug: "dra_aylin_santana_ortiz",
    name: "Dra. Aylin Santana Ortiz",
    specialty: "Nutriología",
    phone: "322 245 1780",
    photo: "/doctors/dra_aylin_santana_ortiz.jpg",
    services: [
      "Historial clínico y mediciones antropométricas",
      "Análisis de bioimpedancia InBody",
      "Diagnóstico nutricional",
      "Plan de alimentación personalizado",
      "Lista de súper",
      "Acceso a app",
    ],
  },
  {
    slug: "dra_sindy_adriana_castillo_vera",
    name: "Dra. Sindy Adriana Castillo Vera",
    specialty: "Psicología Clínica y Educativa · Perito",
    phone: "322 293 6235",
    photo: "/doctors/dra_sindy_adriana_castillo_vera.jpg",
    services: [
      "Terapia familiar, individual, de pareja e infantil",
      "Psicología jurídica y forense",
      "Atención psiquiátrica",
      "Psicodiagnóstico clínico",
      "Trastornos del neurodesarrollo",
      "Animales de apoyo emocional",
      "Perito en psicología",
    ],
  },
  {
    slug: "dr_fernando_cantu",
    name: "Dr. Fernando Cantú",
    specialty: "Especialista",
    phone: "322 293 6235",
    photo: "/doctors/dr_fernando_cantu.jpg",
    services: [],
  },
  {
    slug: "dr_uriel_daniel_munoz_gonzalez",
    name: "Dr. Uriel Daniel Muñoz González",
    specialty: "Especialista",
    phone: "322 293 6235",
    photo: "/doctors/dr_uriel_daniel_munoz_gonzalez.jpg",
    services: [],
  },
  {
    slug: "dra_roxana_proviquer",
    name: "Dra. Roxana J. Vázquez / Enf. Weena Amieva",
    specialty: "Heridas y Ostomías — Proviquer",
    phone: "322 143 9528",
    photo: "/doctors/proviquer.jpg",
    services: [
      "Atención a personas con heridas y ostomías",
      "Consulta médica general",
    ],
  },
  {
    slug: "bios_lab",
    name: "BIOS LAB",
    specialty: "Laboratorio Clínico",
    phone: "322 293 8173",
    photo: "/doctors/bios_lab.jpg",
    services: [
      "Biometría hemática",
      "Examen general de orina",
      "Perfil cardíaco y hepático",
      "Perfil tiroideo y ovárico",
      "Perfil prenatal y metabólico",
      "Perfil diabético",
      "Perfil de transmisión sexual",
      "Perfil de daño renal temprano",
    ],
  },
];

export const WHY = {
  badge: "¿Por qué elegirnos?",
  headline: "¿Por qué elegir Madeira Medical Group?",
  cards: [
    {
      icon: "📍",
      title: "Excelente Ubicación",
      description:
        "Ubicados en Versalles, el barrio más reconocido de Puerto Vallarta, con la mayor densidad de flujo de pacientes locales e internacionales.",
    },
    {
      icon: "✈️",
      title: "Turismo Médico",
      description:
        "Puerto Vallarta es el destino mejor posicionado a nivel nacional para el turismo médico. Tus pacientes te encontrarán desde cualquier parte del mundo.",
    },
    {
      icon: "🗓️",
      title: "Gestión de Consultas",
      description:
        "Secretaria y sistema de gestión de citas incluidos. Enfócate en tus pacientes, nosotros nos encargamos de la operación.",
    },
    {
      icon: "📈",
      title: "Retorno de Inversión Inmediato",
      description:
        "Saque el máximo provecho de su ubicación dentro de Punto Madeira, complejo residencial y comercial con 55 familias.",
    },
  ],
};

export const CONTACT = {
  badge: "Contacto",
  headline: "Habla con nosotros hoy",
  body: "Nuestro equipo está listo para asesorarte y mostrarte los consultorios disponibles sin compromiso.",
  formFields: {
    name: "Tu nombre completo",
    email: "Correo electrónico",
    phone: "Teléfono / WhatsApp",
    specialty: "Especialidad médica",
    message: "Mensaje (opcional)",
  },
  submitLabel: "Enviar mensaje",
};

export const FOOTER = {
  tagline: "Consultorios médicos premium en Puerto Vallarta.",
  links: [
    { label: "Inicio", href: "#inicio" },
    { label: "Rentar Consultorio", href: "#renta" },
    { label: "Especialidades", href: "#especialidades" },
    { label: "Médicos", href: "#medicos" },
    { label: "Contacto", href: "#contacto" },
  ],
  copyright: `© ${new Date().getFullYear()} Madeira Medical Group. Todos los derechos reservados.`,
  credit: "Desarrollado por HOMIA Digital",
};
